# -*- coding: utf-8 -*-
"""aws_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHYHynSddLlLRES7PkO_-qh_eOdy5IKT
"""

#!pip install boto3

import boto3

# Initialize AWS client
sagemaker_client = boto3.client(
    "sagemaker",
    region_name="us-east-2",  # or your region
    aws_access_key_id = "YOUR_ACCESS_KEY_ID"
aws_secret_access_key = "YOUR_SECRET_ACCESS_KEY"
)

# Let's just test by listing models to make sure it's connected
models = sagemaker_client.list_models()
for model in models['Models']:
    print(model['ModelName'])

import boto3
import json

# Connect to SageMaker runtime client
runtime_client = boto3.client(
    "sagemaker-runtime",
    region_name="us-east-2",  # your AWS region
    aws_access_key_id = "YOUR_ACCESS_KEY_ID"
aws_secret_access_key = "YOUR_SECRET_ACCESS_KEY"
)

# Your SageMaker endpoint name
endpoint_name = "bert-fake-news-endpoint"

def predict_headlines(headlines):
    payload = {
        "inputs": headlines
    }

    response = runtime_client.invoke_endpoint(
        EndpointName=endpoint_name,
        ContentType="application/json",
        Body=json.dumps(payload)
    )

    predictions = json.loads(response['Body'].read())

    for text, pred in zip(headlines, predictions):
        label = "REAL 📰" if pred == 0 else "FAKE 🚨"
        print(f"'{text}' --> {label}")

# Main menu loop
def main_menu():
    print("📰🚨 Welcome to the Fake News Detector 🚨📰")
    while True:
        print("\nMenu:")
        print("1. Check a single news headline")
        print("2. Check multiple news headlines")
        print("3. Exit")

        choice = input("Enter your choice (1/2/3): ")

        if choice == '1':
            headline = input("\nEnter the news headline: ")
            predict_headlines([headline])  # Wrap single headline in a list

        elif choice == '2':
            try:
                num = int(input("\nHow many headlines would you like to check? "))
                headlines = []
                for i in range(num):
                    h = input(f"Enter headline {i+1}: ")
                    headlines.append(h)
                predict_headlines(headlines)
            except ValueError:
                print("⚠️ Please enter a valid number.")

        elif choice == '3':
            print("\nThank you for using the Fake News Detector! 👋")
            break

        else:
            print("⚠️ Invalid choice. Please select 1, 2, or 3.")

# Run the app
main_menu()